baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'kchmielewski.xyz'

[params]
 dateFormat = "Jan 2, 2006"

[taxonomies]
 author = "author"
 tags = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false 
    noClasses = false
    noHl = false
    style = ''
    tabWidth = 2


